Repository mini-project-team3/BE, pull requests merged in 2023-02, with the labels that each got.

#16 #13 response dto
  src/main/java/com/sparta/be/common/ApiResponseDto.java
  src/main/java/com/sparta/be/common/ErrorResponse.java
  src/main/java/com/sparta/be/common/ResponseUtils.java
  src/main/resources/application.properties
Labels: enhancement

#28 feat:#9 로그인 @Transactional에 readOnly = true 추가
  src/main/java/com/sparta/be/service/UserService.java
Labels: refactor

#33 feat: #12 연관관계 @JoinColumn 으로 수정
  src/main/java/com/sparta/be/entity/Comment.java
Labels: fix

#35 setting: validation dependency 추가
  build.gradle
  src/main/java/com/sparta/be/controller/UserController.java
  src/main/java/com/sparta/be/dto/SignupRequestDto.java
Labels: setting

#36 feat: #12 생성자 추가
  src/main/java/com/sparta/be/entity/Comment.java
Labels: enhancement

#37 #6 get all reviews
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/dto/CommentResponseDto.java
  src/main/java/com/sparta/be/dto/ReviewDetailResponseDto.java
  src/main/java/com/sparta/be/dto/ReviewResponseDto.java
  src/main/java/com/sparta/be/entity/Review.java
  src/main/java/com/sparta/be/repository/ReviewRepository.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: enhancement

#39 #32 category review
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/dto/ReviewRequestDto.java
  src/main/java/com/sparta/be/entity/CategoryType.java
  src/main/java/com/sparta/be/entity/Review.java
  src/main/java/com/sparta/be/repository/ReviewRepository.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: enhancement

#42 #32 category
  src/main/java/com/sparta/be/entity/Category.java
  src/main/java/com/sparta/be/entity/Review.java
  src/main/java/com/sparta/be/entity/ReviewCategory.java
  src/main/java/com/sparta/be/repository/CategoryRepository.java
  src/main/java/com/sparta/be/repository/ReviewCategoryRepository.java
  src/main/java/com/sparta/be/repository/ReviewRepository.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: enhancement

#43 feat: #10 내가 쓴 리뷰 조회 API 구현
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/repository/ReviewRepository.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: enhancement

#48 #44 exception
  src/main/java/com/sparta/be/common/ErrorResponse.java
  src/main/java/com/sparta/be/common/ErrorType.java
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/controller/UserController.java
  src/main/java/com/sparta/be/dto/SignupRequestDto.java
  src/main/java/com/sparta/be/exception/CustomExceptionHandler.java
  src/main/java/com/sparta/be/service/ReviewService.java
  src/main/java/com/sparta/be/service/UserService.java
Labels: enhancement

#49 feat: #12 update 매서드 추가
  src/main/java/com/sparta/be/entity/Comment.java
Labels: enhancement

#53 feat: #51 cors 적용
  src/main/java/com/sparta/be/config/WebSecurityConfig.java
  src/main/java/com/sparta/be/service/UserService.java
Labels: setting

#55 feat: #54 ApiResponseDto 제네릭스 타입 설정
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/controller/UserController.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: refactor

#60 feat: #11 내가 좋아요한 리뷰 조회 API 구현
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/repository/ReviewRepository.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: enhancement

#64 Feat: #63 닉네임 중복 시 예외 처리 구현
  src/main/java/com/sparta/be/common/ErrorType.java
  src/main/java/com/sparta/be/controller/UserController.java
  src/main/java/com/sparta/be/dto/SignupRequestDto.java
  src/main/java/com/sparta/be/entity/Category.java
  src/main/java/com/sparta/be/entity/Review.java
  src/main/java/com/sparta/be/repository/UserRepository.java
  src/main/java/com/sparta/be/service/UserService.java
  src/main/resources/application-db.yml
Labels: enhancement

#65 feat : #44 좋아요 부분 exception 처리 적용
  src/main/java/com/sparta/be/common/ErrorType.java
  src/main/java/com/sparta/be/controller/LikeCommentController.java
  src/main/java/com/sparta/be/controller/LikeReviewController.java
  src/main/java/com/sparta/be/service/LikeCommnetService.java
  src/main/java/com/sparta/be/service/LikeReviewService.java
Labels: enhancement

#66 #62 reviews
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/service/ReviewService.java
Labels: refactor

#70 #44 #54 #62 변경사항
  src/main/java/com/sparta/be/common/FailureResponseDto.java
  src/main/java/com/sparta/be/common/ResponseUtils.java
  src/main/java/com/sparta/be/common/SuccessResponseDto.java
  src/main/java/com/sparta/be/controller/CommentController.java
  src/main/java/com/sparta/be/controller/LikeCommentController.java
  src/main/java/com/sparta/be/controller/LikeReviewController.java
  src/main/java/com/sparta/be/controller/ReviewController.java
  src/main/java/com/sparta/be/controller/UserController.java
  src/main/java/com/sparta/be/exception/CustomExceptionHandler.java
  src/main/java/com/sparta/be/service/CommentService.java
  src/main/java/com/sparta/be/service/LikeCommnetService.java
  src/main/java/com/sparta/be/service/LikeReviewService.java
  src/main/java/com/sparta/be/service/ReviewService.java
  src/main/java/com/sparta/be/service/UserService.java
Labels: refactor
